import { MenuItem } from '@/lib/types';

export const menuItems: MenuItem[] = [
  // Breakfast Menu (10 items)
  {
    name: 'Traditional Breakfast',
    slug: 'traditional-breakfast',
    category: 'breakfast-menu',
    description: 'Start your morning properly with this hearty traditional classic. It features a perfectly fried egg with a beautiful runny yolk, crispy back bacon, and a succulent Lincolnshire sausage. Alongside, you will find a generous portion of baked beans, two golden hash browns with a satisfying crunch, and a fresh slice of toast with butter. The rich and comforting flavours make this an absolute must for anyone seeking a familiar start to the day. It is an ideal choice for early risers needing fuel for the morning. Served on a warm plate to ensure every bite is comforting.',
    typicalPriceGbp: 5.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 770,
    allergens: ['eggs'],
    dietaryTags: [],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Large Breakfast',
    slug: 'large-breakfast',
    category: 'breakfast-menu',
    description: 'Designed for the biggest appetites, this magnificent morning feast doubles down on the classics. You will enjoy two perfectly fried eggs, two slices of crispy bacon, and two Lincolnshire sausages. Accompanied by baked beans, three crunchy hash browns, an earthy flat mushroom, a grilled tomato half, and two slices of toast with butter. The combination of savoury, salty, and rich flavours creates a truly indulgent texture profile. This is the ultimate choice for weekend brunch enthusiasts or those recovering from a lively night out. Best enjoyed with a hot cup of filter coffee.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1320,
    allergens: ['eggs'],
    dietaryTags: [],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegetarian Breakfast',
    slug: 'vegetarian-breakfast',
    category: 'breakfast-menu',
    description: 'A magnificent meat-free morning feast that refuses to compromise on flavour or satisfaction. It features a freshly fried egg with a glorious golden yolk, two tasty Quorn vegetarian sausages, and a generous helping of baked beans. These are served alongside two crispy hash browns, a juicy roasted tomato, an earthy flat mushroom, and a slice of warm toast. The savoury profile of the sausages pairs wonderfully with the comforting crunch of the hash browns. This dish is excellent for vegetarians or anyone looking for a slightly lighter, yet deeply fulfilling breakfast option. Served piping hot.',
    typicalPriceGbp: 5.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 725,
    allergens: ['eggs'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegan Breakfast',
    slug: 'vegan-breakfast',
    category: 'breakfast-menu',
    description: 'Experience plant-based breakfast goodness with this thoughtfully crafted morning plate. It stars two savoury vegan sausages packed with flavour, paired with classic baked beans, two wonderfully crisp hash browns, an earthy roasted flat mushroom, and a grilled tomato half. Accompanied by a slice of toast served with a smooth vegan spread. The texture contrasts beautifully between the crunchy potatoes and the tender sausages. It is an ideal selection for vegans and flexitarians seeking a wholesome, cruelty-free start to their day. A hearty option that leaves you fully satisfied without feeling overly heavy.',
    typicalPriceGbp: 5.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 680,
    allergens: ['eggs'],
    dietaryTags: ['vegan', 'vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Eggs Benedict',
    slug: 'eggs-benedict',
    category: 'breakfast-menu',
    description: 'A timeless breakfast indulgence featuring two perfectly poached eggs with beautiful runny yolks and thick slices of Wiltshire cured ham. These are carefully arranged atop a lightly toasted, soft English muffin. The entire dish is then draped in a rich, buttery hollandaise sauce that adds a luxurious, tangy finish. The delicate texture of the eggs contrasts perfectly with the chewiness of the muffin and the savoury bite of the ham. Ideal for those who desire a sophisticated yet comforting brunch. It arrives exquisitely presented, making it a wonderful weekend treat to savour.',
    typicalPriceGbp: 5.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 612,
    allergens: ['eggs'],
    dietaryTags: [],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Mushroom Benedict',
    slug: 'mushroom-benedict',
    category: 'breakfast-menu',
    description: 'A delightful vegetarian twist on a brunch classic, showcasing two beautifully poached eggs alongside earthy, roasted flat mushrooms. These sit elegantly on a warm, toasted English muffin, all generously coated in a luscious, buttery hollandaise sauce. The deep, umami flavours of the mushrooms blend seamlessly with the creamy sauce and the rich egg yolks, creating a melt-in-the-mouth texture. This is a brilliant choice for vegetarians seeking a decadent morning option or anyone wanting a slightly lighter Benedict variation. Served fresh and warm, it is perfect for a leisurely mid-morning meal.',
    typicalPriceGbp: 5.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'eggs', 'milk', 'soybeans'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Beans on Toast',
    slug: 'beans-on-toast',
    category: 'breakfast-menu',
    description: 'A comforting and deeply satisfying British staple that always hits the spot. A generous portion of piping hot, rich baked beans is piled high atop your choice of freshly toasted white or malted bread, spread with melting butter. The sweetness of the tomato sauce perfectly soaks into the crisp toast, offering a wonderful balance of soft and crunchy textures. Simple, hearty, and nostalgic, this dish is fantastic for a quick, uncomplicated breakfast or a warming snack on a chilly morning. Served steaming hot, it is a true testament to the beauty of simple ingredients.',
    typicalPriceGbp: 3.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk', 'soybeans'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Breakfast Wrap',
    slug: 'breakfast-wrap',
    category: 'breakfast-menu',
    description: 'A convenient and incredibly tasty morning option encased in a soft, gently toasted tortilla wrap. Inside, you will discover a glorious combination of a fried egg, crispy bacon, a savoury Lincolnshire sausage, and a golden hash brown. The soft tortilla provides a delightful contrast to the crunchy potato and the rich, meaty fillings, creating a wonderfully portable breakfast experience. It is the perfect choice for those with a busy morning ahead or anyone who prefers their breakfast components in one delicious bite. Served warm, it is a superb on-the-go or relaxed dining option.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 540,
    allergens: ['cereals containing gluten', 'eggs'],
    dietaryTags: [],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegetarian Breakfast Wrap',
    slug: 'vegetarian-breakfast-wrap',
    category: 'breakfast-menu',
    description: 'A fantastic meat-free morning bite wrapped in a soft, warm flour tortilla. This tasty parcel is generously packed with a freshly fried egg, two savoury Quorn vegetarian sausages, two crispy hash browns, and a layer of melting cheddar cheese. The combination of the gooey cheese, soft egg, and crunchy potatoes creates a deeply satisfying texture and a rich, comforting flavour profile. Excellent for vegetarians seeking a substantial yet easily manageable breakfast. It is a brilliant grab-and-go choice or a delightful sit-down treat to pair with your morning cup of tea.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 725,
    allergens: ['cereals containing gluten', 'eggs'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Porridge with Honey',
    slug: 'porridge-honey',
    category: 'breakfast-menu',
    description: 'A wonderfully warm and wholesome bowl of traditional porridge oats, cooked until perfectly creamy and smooth. This comforting dish is elevated by a generous drizzle of sweet, golden honey that melts gently into the oats, creating a delicate and soothing flavour profile. The soft, rich texture provides a gentle start to the day that is both satisfying and nutritious. It is an excellent choice for a lighter breakfast or for warming up on a crisp, frosty morning. Served steaming in a deep bowl, it is a classic option that never goes out of style.',
    typicalPriceGbp: 3.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 285,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Served 8am to 12 noon daily',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  
  // Burgers (12 items)
  {
    name: 'Classic 6oz Beef Burger',
    slug: 'classic-6oz-beef-burger',
    category: 'burgers',
    description: 'A straightforward yet incredibly satisfying classic pub burger featuring a thick, juicy 6oz beef patty. The meat is nestled inside a soft, lightly toasted bun alongside crisp fresh lettuce, a slice of ripe tomato, and thinly sliced red onion. It comes accompanied by a generous portion of our famous golden chips. The savoury, meaty flavours shine through, perfectly balanced by the crunch of the fresh salad. This is the ideal choice for purists who appreciate a traditional, unfussy burger experience. Served hot and fresh, it is a timeless meal that always delivers on taste.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1143,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Skinny 6oz Beef Burger',
    slug: 'skinny-6oz-beef-burger',
    category: 'burgers',
    description: 'A lighter take on our classic pub favourite, featuring the same fantastic, juicy 6oz beef patty. Served in a soft bun with crisp lettuce, fresh tomato, and red onion, but accompanied by a refreshing side salad in place of chips. The salad includes a light vinaigrette dressing, offering a crisp, tangy contrast to the rich, savoury beef. This is an excellent option for those wanting a fulfilling, meaty lunch without the heaviness of potatoes. It provides a wonderful balance of indulgence and freshness, making it a superb choice for a weekday lunch.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'American Cheese Burger',
    slug: 'american-cheese-burger',
    category: 'burgers',
    description: 'The quintessential diner experience brought straight to your table. A succulent 6oz beef patty is topped with a layer of melting American-style cheese, tangy sliced gherkins, sweet ketchup, and a touch of mild mustard. Encased in a soft bun and served with a hearty portion of golden chips. The flavour profile perfectly balances the rich, savoury beef with the sharp tang of mustard and pickles, creating an incredibly satisfying bite. It is a fantastic choice for anyone craving a classic, nostalgic American flavour. Served piping hot, it is guaranteed to hit the spot.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1350,
    allergens: ['cereals containing gluten', 'milk', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Double American Cheese Burger',
    slug: 'double-american-cheese-burger',
    category: 'burgers',
    description: 'An absolute triumph for burger enthusiasts, this towering creation features two thick, juicy beef patties stacked high. Generously layered with double the melting American-style cheese, crisp gherkins, rich ketchup, and tangy mustard, all within a soft toasted bun. Accompanied by a magnificent portion of our signature chips. The double helping of beef and cheese creates an incredibly rich and decadent texture, delivering an intense, savoury punch. This is strictly for those with a serious appetite and a love for classic diner flavours. Served fresh and hot, it is a truly monumental meal.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1450,
    allergens: ['cereals containing gluten', 'milk', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'BBQ Bacon Burger',
    slug: 'bbq-bacon-burger',
    category: 'burgers',
    description: 'A mouth-watering combination of sweet, smoky, and savoury flavours that is sure to delight. This burger features a juicy 6oz beef patty layered with melting cheddar cheese, strips of crispy maple-cured bacon, and a generous smothering of rich, smoky BBQ sauce. Served in a soft bun alongside a hearty portion of golden chips. The crunch of the bacon against the soft bun and tender beef creates a deeply satisfying texture. It is a brilliant choice for those who love bold, barbecue-inspired tastes. Served hot, it is a perfect evening treat paired with a cold pint.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1290,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Empire State Burger',
    slug: 'empire-state-burger',
    category: 'burgers',
    description: 'A truly towering beast of a burger designed to conquer the grandest of appetites. This colossal creation contains two thick 6oz beef patties, layers of melting American-style cheese, and crispy maple-cured bacon. Served in a soft bun with a mountain of golden chips on the side. The sheer volume of savoury beef and rich cheese delivers an incredibly dense and satisfying texture, with a flavour profile that is unabashedly bold and meaty. It is the ultimate challenge for hungry diners looking for a spectacular feast. Arrives impressively stacked and ready to be devoured.',
    typicalPriceGbp: 9.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1883,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Fried Buttermilk Chicken Burger',
    slug: 'fried-buttermilk-chicken-burger',
    category: 'burgers',
    description: 'A delightfully crispy and tender option featuring a plump chicken breast that has been marinated in buttermilk and coated in a seasoned, crunchy breading. Served inside a soft bun with crisp fresh lettuce, a slice of tomato, and a layer of creamy mayonnaise, alongside a portion of chips. The contrast between the incredibly crispy exterior and the juicy, tender chicken inside makes for a fantastic texture. This is a superb choice for anyone looking for a comforting, satisfying alternative to beef. Served piping hot, it offers a wonderful harmony of crunch and creaminess.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 980,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Grilled Chicken Breast Burger',
    slug: 'grilled-chicken-breast-burger',
    category: 'burgers',
    description: 'A simple, honest, and wonderfully satisfying choice featuring a tender, perfectly grilled chicken breast. Served in a soft toasted bun with crisp fresh lettuce and ripe tomato, accompanied by a hearty helping of our classic chips. The clean, roasted flavours of the chicken are complemented by the crunch of the fresh salad, offering a lighter yet deeply fulfilling meal. It is an excellent option for those who prefer a more straightforward, less heavy burger experience. Served fresh from the grill, it is a reliable and delicious staple for any time of the day.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 980,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Skinny Chicken Burger',
    slug: 'skinny-chicken-burger',
    category: 'burgers',
    description: 'A wonderfully light and refreshing take on our classic poultry offering. A tender, perfectly grilled chicken breast is served in a soft bun alongside crisp lettuce and fresh tomato, but partnered with a vibrant side salad instead of chips. The crisp greens and light vinaigrette dressing provide a zesty contrast to the warm, savoury chicken. This is the perfect choice for diners looking for a satisfying, high-protein meal that remains beautifully light and fresh. It is an ideal lunch option for a busy day, delivering all the flavour without any of the heaviness.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 980,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Beyond Meat Plant-Based Burger',
    slug: 'beyond-meat-burger',
    category: 'burgers',
    description: 'A phenomenal plant-based creation that delivers all the satisfaction of a traditional burger. Featuring a juicy, flavour-packed Beyond Meat patty that cooks and tastes remarkably like beef. It is served in a soft bun with fresh vegan lettuce, sliced tomato, and red onion, accompanied by a generous portion of chips. The texture is wonderfully dense and satisfying, offering a rich, savoury profile with a subtle smoky undertone. This is a must-try for vegans, vegetarians, or anyone curious about high-quality meat alternatives. Served hot, it is a brilliant and environmentally friendly pub classic.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 856,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Fiesta Burger',
    slug: 'fiesta-burger',
    category: 'burgers',
    description: 'A vibrant and flavourful plant-based delight that brings a burst of colour to your plate. This burger features a succulent Beyond Meat patty topped generously with sweet roasted red peppers, tender courgettes, and onions, all finished with a slightly spicy, tangy salsa. Served in a bun with a side of golden chips. The sweet and smoky vegetables contrast beautifully with the savoury, meaty texture of the patty, creating a lively and exciting flavour profile. It is a fantastic choice for those who want a hearty vegan meal with a vibrant, Mediterranean-inspired twist.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 856,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Breaded Vegetable Burger',
    slug: 'breaded-vegetable-burger',
    category: 'burgers',
    description: 'A comforting and wholesome vegetarian option boasting a delightful, crispy breadcrumb coating. Inside, you will find a savoury blend of tender lentils, sweet carrots, and juicy sweetcorn. Served in a soft bun with crisp lettuce and tomato, accompanied by a hearty serving of chips. The exterior offers a deeply satisfying crunch that yields to a soft, earthy, and slightly sweet vegetable filling. This is a superb choice for those wanting a traditional, uncomplicated veggie burger packed with familiar flavours. Served hot, it is a reliable and tasty meat-free alternative that never disappoints.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 856,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Pizza (8 items)
  {
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    category: 'pizza',
    description: 'A timeless Italian classic that celebrates the beauty of simple, high-quality ingredients. Our thin, crisp pizza base is generously coated with a rich and tangy tomato sauce, before being blanketed in melting, gooey mozzarella cheese and finished with a scattering of fresh basil. The flavour profile is a perfect harmony of sweet tomatoes, creamy cheese, and aromatic herbs, while the crust provides a wonderful crunch. It is an excellent choice for vegetarians or anyone seeking a light, uncomplicated, yet incredibly satisfying meal. Served piping hot straight from the oven, it is perfect for sharing.',
    typicalPriceGbp: 5.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 959,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Pepperoni Pizza',
    slug: 'pepperoni-pizza',
    category: 'pizza',
    description: 'A universally beloved favourite featuring a generous topping of savoury, slightly spicy sliced pepperoni. The meat is arranged over a rich tomato sauce and a thick layer of melting mozzarella, all resting on a thin and crispy pizza base. As it bakes, the pepperoni edges turn delightfully crisp, releasing their rich, smoky oils into the creamy cheese. This creates an intensely flavourful and satisfying bite with a wonderful texture contrast. It is the ideal choice for meat lovers seeking a hearty and comforting pizza. Served fresh and hot, it pairs brilliantly with a cold beer.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1111,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'BBQ Chicken Pizza',
    slug: 'bbq-chicken-pizza',
    category: 'pizza',
    description: 'A sweet, smoky, and deeply satisfying pizza experience with a distinctly Southern twist. This pizza replaces the traditional tomato base with a rich, smoky BBQ sauce, generously topped with melting mozzarella, tender roasted chicken breast pieces, crispy bacon, and thinly sliced red onions. The sweetness of the sauce pairs magnificently with the savoury meats and the sharp crunch of the onions. It is a fantastic choice for diners who prefer bold, sweet-savoury flavour profiles over classic Italian styles. Served piping hot, the robust flavours make it a standout choice for a satisfying evening meal.',
    typicalPriceGbp: 7.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1050,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Spicy Meat Feast Pizza',
    slug: 'spicy-meat-feast-pizza',
    category: 'pizza',
    description: 'An absolute triumph for dedicated carnivores, packing a serious punch of flavour and heat. Our thin, crisp base is loaded with a rich tomato sauce, mozzarella, sliced pepperoni, tender chicken breast, crispy bacon, spicy sausage, and fiery roquito peppers. The flavour profile is intensely savoury, smoky, and wonderfully spicy, with the peppers providing a sharp, sweet heat that cuts through the rich meats. This is the ultimate choice for those with a large appetite and a love for bold, fiery flavours. Served fresh from the oven, it is a truly monumental pizza experience.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1250,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Roasted Vegetable Pizza',
    slug: 'roasted-vegetable-pizza',
    category: 'pizza',
    description: 'A delightful and colourful vegetarian option that bursts with natural sweetness and earthy flavours. A thin, crispy base is coated with a tangy tomato sauce and melting mozzarella, then generously topped with a medley of tender roasted peppers, soft courgettes, and sweet red onions. The roasting process caramelises the vegetables, enhancing their natural sugars, which balances beautifully with the creamy cheese and crisp crust. It is a fantastic choice for those seeking a lighter, vegetable-forward meal that remains deeply comforting. Served piping hot, it is a brilliant and flavourful meat-free alternative.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 980,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegan Roasted Vegetable Pizza',
    slug: 'vegan-roasted-vegetable-pizza',
    category: 'pizza',
    description: 'A fantastic plant-based pizza that refuses to compromise on taste or texture. Our crisp pizza base is spread with a rich tomato sauce and topped with a melting, vegan-friendly cheese alternative. It is then loaded with a vibrant mix of sweet roasted peppers, tender courgettes, and onions. The vegan cheese provides a creamy, savoury finish that beautifully complements the natural sweetness of the roasted vegetables. This is an excellent choice for vegans or those with dairy intolerances looking for a comforting, authentic pizza experience. Served fresh and hot, it is deeply satisfying.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 890,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Hawaiian Pizza',
    slug: 'hawaiian-pizza',
    category: 'pizza',
    description: 'A controversial yet undeniable classic that perfectly balances sweet and savoury notes. Our thin, crispy base is layered with a rich tomato sauce and melting mozzarella, then topped with thick slices of Wiltshire cured ham and juicy chunks of sweet pineapple. The flavour profile is a delightful contrast; the salty, savoury ham cuts through the bright, acidic sweetness of the fruit, all brought together by the creamy cheese. It is an ideal choice for diners who love a playful, sweet-savoury combination. Served hot from the oven, it remains a steadfast and popular favourite.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1020,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Chicken & Rib Meat Pizza',
    slug: 'chicken-rib-meat-pizza',
    category: 'pizza',
    description: 'A phenomenally rich and satisfying pizza designed for serious meat lovers. This creation features a tomato and mozzarella base generously topped with succulent, spicy chicken strips and tender, pulled pork rib meat, all finished with a delightful drizzle of creamy garlic mayonnaise. The smoky, sweet flavours of the pulled pork blend seamlessly with the spiced chicken, while the garlic mayo adds a luxurious, tangy finish. The texture is incredibly hearty and mouth-coating. It is a superb choice for those craving a decadent, flavour-packed feast. Served hot, it is a truly indulgent pub treat.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1250,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Chicken Dishes (7 items)
  {
    name: 'Chicken Jalfrezi',
    slug: 'chicken-jalfrezi',
    category: 'chicken-dishes',
    description: 'A vibrant and hearty curry that delivers a wonderful complexity of flavours and a satisfying kick of heat. Tender pieces of marinated chicken are cooked in a robust sauce packed with aromatic spices, fresh green chillies, and crisp mixed peppers. Accompanied by a portion of fragrant pilau rice, a soft, warm naan bread, and crisp poppadums. The dish offers a brilliant contrast between the rich, spicy sauce and the cooling, fluffy rice. It is an excellent choice for curry enthusiasts who appreciate a lively, warming spice profile. Served steaming hot, it is deeply comforting.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['milk', 'mustard'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Southern-Fried Chicken Strips Basket',
    slug: 'southern-fried-chicken-strips-basket',
    category: 'chicken-dishes',
    description: 'A fantastic, informal meal featuring five succulent chicken breast strips coated in a wonderfully seasoned, slightly spiced Southern-fried breadcrumb. Served in a basket alongside a generous portion of golden chips and your choice of a cooling dipping sauce. The exterior of the chicken provides a deeply satisfying crunch, giving way to tender, juicy meat inside. The subtle blend of herbs and spices offers a warm, savoury flavour profile without being overly hot. It is the perfect choice for a relaxed lunch or a casual dinner, offering brilliant comfort food that is easy to enjoy.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 780,
    allergens: ['cereals containing gluten', 'milk', 'eggs'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Chicken Breast Bites Basket',
    slug: 'chicken-breast-bites-basket',
    category: 'chicken-dishes',
    description: 'A delightful and moreish option featuring bite-sized pieces of premium chicken breast, encased in a light, crispy batter. Presented in a basket with a hearty serving of chips and a dipping sauce of your choice. The batter is wonderfully golden and crunchy, providing a fantastic textural contrast to the soft, juicy chicken within. The flavour is gently savoury, allowing the quality of the chicken to shine, while the dip adds a welcome tang. This is an excellent, fuss-free choice for those seeking a comforting, familiar pub classic. Served hot, it is always a crowd-pleaser.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk', 'eggs'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Lemon and Herb Half Chicken',
    slug: 'lemon-herb-half-chicken',
    category: 'chicken-dishes',
    description: 'A remarkably succulent and flavourful dish featuring half a chicken that has been carefully marinated in a zesty, aromatic blend of fresh lemon and fragrant herbs. It is roasted until the skin is beautifully golden and served with a side of crunchy coleslaw and a generous portion of chips. The citrus notes cut through the richness of the chicken, providing a bright, refreshing flavour profile, while the meat remains incredibly tender. It is a fantastic choice for diners wanting a substantial, hearty meal with a vibrant, fresh twist. Served piping hot.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['milk', 'eggs'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Spicy Peri-Peri Half Chicken',
    slug: 'spicy-peri-peri-half-chicken',
    category: 'chicken-dishes',
    description: 'A vibrant and fiery option that brings a wonderful depth of flavour and a decent kick of heat. This generous half chicken is thoroughly marinated in a robust, spicy peri-peri sauce and roasted until the skin is beautifully charred and crisp. Served alongside our classic golden chips and a portion of creamy coleslaw to cool the palate. The meat is incredibly juicy, absorbing the smoky, tangy, and hot notes of the marinade perfectly. It is the ultimate choice for those who love bold, lively spices and a deeply satisfying, meaty feast.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['milk', 'eggs'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: '10 Spicy Chicken Wings',
    slug: 'spicy-chicken-wings',
    category: 'chicken-dishes',
    description: 'A fantastic sharing option or a hearty meal for one, featuring a generous portion of ten crispy, deeply flavoured chicken wings. Each wing is coated in a spicy, tangy seasoning that delivers a satisfying, lingering heat. Served with a choice of a cool blue cheese or garlic dip, which provides a wonderfully creamy contrast to the fiery wings. The texture is perfectly crisp on the outside, yielding to tender, juicy meat. This is an excellent choice for pairing with a cold pint of lager or for enjoying during a lively evening out. Served piping hot.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 620,
    allergens: ['milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Quorn No Chicken Nuggets Basket',
    slug: 'quorn-nuggets-basket',
    category: 'chicken-dishes',
    description: 'A brilliant plant-based alternative that delivers all the comfort and satisfaction of traditional chicken nuggets. This basket contains eight golden, crispy Quorn vegan nuggets that offer a remarkably authentic texture and a savoury, fulfilling flavour. Served with a hearty portion of chips and a sticky, sweet chilli dipping sauce for a welcome tangy kick. The crunch of the coating pairs wonderfully with the soft, tender interior. It is an ideal choice for vegans, vegetarians, or anyone looking for a familiar, casual pub meal without the meat. Served hot, it is completely fuss-free and delicious.',
    typicalPriceGbp: 6.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 844,
    allergens: ['cereals containing gluten', 'soybeans'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Curry Club (7 items)
  {
    name: 'Chicken Tikka Masala',
    slug: 'chicken-tikka-masala',
    category: 'curry-club',
    description: 'The nation’s beloved curry classic, offering a wonderfully rich, creamy, and mildly spiced experience. Tender pieces of marinated chicken are simmered in a luscious tomato-based sauce, enriched with cream and a delicate blend of aromatic spices. Served alongside fluffy pilau rice and a warm, soft naan bread to mop up every last drop of the sauce. The flavour profile is beautifully balanced—sweet, earthy, and highly comforting with a velvety texture. It is the perfect choice for those who prefer a milder, deeply flavourful curry. Served steaming hot, it is a definitive pub favourite.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1158,
    allergens: ['milk', 'mustard'],
    dietaryTags: [],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Beef Madras',
    slug: 'beef-madras',
    category: 'curry-club',
    description: 'A robust, rich, and fairly hot curry designed for those who appreciate a bolder spice profile. Chunks of incredibly tender beef are slow-cooked in a dark, intensely savoury sauce packed with tomatoes, fiery chillies, and deep, earthy spices. The long cooking time ensures the beef melts in the mouth, while the sauce provides a complex, lingering heat. Accompanied by fragrant rice and a soft naan bread. This is an excellent choice for spice enthusiasts looking for a highly satisfying, warming dish with a profound depth of flavour. Served piping hot.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 720,
    allergens: ['milk', 'mustard'],
    dietaryTags: [],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Mangalorean Roasted Cauliflower & Spinach Curry',
    slug: 'mangalorean-cauliflower-spinach-curry',
    category: 'curry-club',
    description: 'A fantastic, vibrant plant-based curry that showcases a wonderful array of earthy and aromatic flavours. It combines beautifully roasted cauliflower florets and tender fresh spinach, all simmered in a fragrant, creamy coconut sauce infused with South Indian spices. Served with fluffy rice and a warm naan. The roasted cauliflower adds a gentle nuttiness and a satisfying bite, contrasting perfectly with the rich, smooth sauce. It is an outstanding choice for vegans or anyone seeking a lighter, highly flavourful vegetable curry that is both comforting and aromatic. Served steaming hot.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 680,
    allergens: ['milk', 'mustard'],
    dietaryTags: ['vegan', 'vegetarian'],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Sweet Potato, Chickpea & Spinach Curry',
    slug: 'sweet-potato-chickpea-spinach-curry',
    category: 'curry-club',
    description: 'A beautifully mild and warming plant-based curry that provides deep, wholesome comfort. Generous chunks of sweet potato are combined with tender chickpeas and wilted spinach in a rich, gently spiced tomato and coconut sauce. Accompanied by fragrant rice and a soft naan bread. The natural sweetness of the potato pairs wonderfully with the earthy chickpeas, creating a hearty and deeply satisfying texture. The subtle spice blend ensures a flavourful but gentle heat. It is a brilliant choice for vegans or diners wanting a nutritious, filling, and intensely comforting meal. Served piping hot.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 680,
    allergens: ['milk', 'mustard'],
    dietaryTags: ['vegan', 'vegetarian'],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Katsu Chicken Curry',
    slug: 'katsu-chicken-curry',
    category: 'curry-club',
    description: 'A delightful and incredibly popular Japanese-inspired dish offering a wonderful contrast of textures. A succulent chicken breast escalope, coated in crispy panko breadcrumbs, is sliced and generously smothered in a rich, sweet, and mildly spiced aromatic curry sauce. Served alongside a mound of sticky basmati rice. The crunch of the golden chicken against the velvety, savoury-sweet sauce creates an utterly addictive eating experience. This is an excellent choice for those wanting a mild, highly comforting curry with a satisfying crunch. Served hot, it is a brilliant alternative to traditional British curries.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 844,
    allergens: ['milk', 'mustard'],
    dietaryTags: [],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Katsu Quorn Nugget Curry',
    slug: 'katsu-quorn-nugget-curry',
    category: 'curry-club',
    description: 'A fantastic vegetarian take on the beloved Japanese classic. Eight crispy, golden Quorn nuggets are served atop a bed of basmati rice and drenched in a generous ladle of rich, sweet, and mildly spiced katsu curry sauce. The nuggets provide a wonderful crunch that holds up beautifully against the smooth, aromatic sauce, delivering a highly satisfying, savoury flavour profile. It is an ideal choice for vegetarians or anyone looking for a comforting, meat-free meal with a wonderful blend of sweet and savoury spices. Served steaming hot, it is deeply fulfilling.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 844,
    allergens: ['milk', 'mustard'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Chicken Korma',
    slug: 'chicken-korma',
    category: 'curry-club',
    description: 'An exceptionally mild, sweet, and highly comforting curry that is universally adored. Tender pieces of chicken are gently cooked in a rich, creamy sauce made from coconut, cream, and a very delicate blend of fragrant spices. Served with fluffy white rice and a warm, soft naan bread. The texture is luxuriously velvety, and the flavour profile is distinctively sweet, nutty, and entirely devoid of harsh heat. This is the perfect choice for diners who want a flavourful, aromatic meal without any spiciness, making it highly accessible and deeply satisfying. Served piping hot.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 950,
    allergens: ['milk', 'mustard'],
    dietaryTags: [],
    availabilityNote: 'Curry Club pricing on Thursdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Steak Club (6 items)
  {
    name: '8oz Sirloin Steak',
    slug: '8oz-sirloin-steak',
    category: 'steak-club',
    description: 'A superb, classic steakhouse cut offering a wonderful balance of tenderness and rich beef flavour. This prime 8oz sirloin is expertly grilled to your exact liking, ensuring a beautifully caramelised exterior and a juicy centre. It is served with a hearty accompaniment of golden chips, sweet green peas, a grilled tomato half, and an earthy flat mushroom. The firm texture and pronounced savoury profile make it a steadfast favourite. It is an excellent choice for a celebratory meal or a highly satisfying dinner, pairing exceptionally well with a robust red wine or a dark ale.',
    typicalPriceGbp: 11.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1451,
    allergens: ['mustard', 'sulphur dioxide'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: '14oz Aberdeen Angus Rump Steak',
    slug: '14oz-aberdeen-angus-rump-steak',
    category: 'steak-club',
    description: 'A truly monumental cut of meat designed for the most dedicated steak lovers. This massive 14oz rump steak, sourced from prime Aberdeen Angus beef, boasts an incredibly deep, robust, and beefy flavour profile. Grilled perfectly to your preference, it is served alongside a generous portion of chips, garden peas, a grilled tomato, and a flat mushroom. The rump cut offers a firmer texture that yields an exceptionally rich taste. This is the ultimate choice for a grand, indulgent feast. Served sizzling hot, it demands a hearty appetite and appreciation for quality beef.',
    typicalPriceGbp: 14.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1225,
    allergens: ['mustard', 'sulphur dioxide'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: '5oz Rump Steak',
    slug: '5oz-rump-steak',
    category: 'steak-club',
    description: 'A brilliant option for those seeking the rich flavour of a traditional steak but with a slightly lighter appetite. This neat 5oz rump steak delivers a fantastic, savoury beef punch and a satisfyingly firm texture. Carefully grilled to your liking, it comes complete with golden chips, sweet peas, a grilled tomato, and a flat mushroom. The smaller portion size ensures you can enjoy a high-quality, classic steakhouse experience without feeling overly full. It is an ideal choice for a lunchtime treat or a more modest evening meal, served fresh and hot from the grill.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['mustard', 'sulphur dioxide'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Mixed Grill',
    slug: 'mixed-grill',
    category: 'steak-club',
    description: 'A spectacular and incredibly hearty feast for those who simply cannot decide on just one meat. This generous platter features a thick gammon steak, a tender pork loin, a flavourful rump steak, a succulent lamb chop, and a savoury sausage. The mountain of meat is crowned with a freshly fried egg and served with a large portion of chips. The variety of textures and smoky, grilled flavours provides an immensely satisfying eating experience. It is the absolute perfect choice for an individual with a colossal appetite craving a traditional, unpretentious British pub classic.',
    typicalPriceGbp: 12.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1650,
    allergens: ['cereals containing gluten', 'eggs'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Large Mixed Grill',
    slug: 'large-mixed-grill',
    category: 'steak-club',
    description: 'An expanded, astonishingly generous version of our classic mixed grill, built for the truly ravenous. This monumental plate includes extra cuts of premium steak, additional savoury sausages, gammon, pork loin, and lamb, all topped with two perfectly fried eggs. Naturally, it is accompanied by a massive portion of golden chips. The sheer volume and variety of rich, grilled meats offer an unparalleled savoury indulgence with a diverse range of textures. This is the ultimate carnivore’s challenge, strictly for those seeking the most substantial and meaty feast available on the menu.',
    typicalPriceGbp: 15.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1650,
    allergens: ['cereals containing gluten', 'eggs'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: '10oz Gammon Steak',
    slug: '10oz-gammon-steak',
    category: 'steak-club',
    description: 'A thick, juicy, and wonderfully savoury cut of premium gammon that brings a delightful salty tang to the palate. This substantial 10oz steak is expertly grilled and topped with your choice of two freshly fried eggs or sweet, charred pineapple rings. It is served alongside a hearty portion of chips and sweet garden peas. The firm, meaty texture contrasts beautifully with the soft egg yolk or the acidic sweetness of the pineapple. It is a fantastic, traditional choice for a deeply comforting and filling dinner, served piping hot and full of robust flavour.',
    typicalPriceGbp: 10.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 980,
    allergens: ['mustard', 'sulphur dioxide'],
    dietaryTags: [],
    availabilityNote: 'Steak Club pricing on Tuesdays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Fish Dishes (7 items)
  {
    name: 'Freshly Battered Cod and Chips',
    slug: 'battered-cod-chips',
    category: 'fish-dishes',
    description: 'A truly spectacular portion of our nation’s favourite dish, featuring a massive, responsibly sourced cod fillet. It is coated in a light, incredibly crispy golden batter and freshly fried to perfection, ensuring the thick, flaky white fish inside remains wonderfully moist and tender. Accompanied by a generous heap of thick-cut chips and your choice of traditional mushy or sweet garden peas. The contrast between the salty, crunchy batter and the delicate fish is exceptional. This is the ultimate choice for a comforting, hearty Friday treat or any time you crave a classic British staple.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1288,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    availabilityNote: 'Fish Friday pricing on Fridays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Whitby Breaded Scampi',
    slug: 'whitby-breaded-scampi',
    category: 'fish-dishes',
    description: 'A deeply satisfying and classic seaside treat featuring plump, premium whole-tail scampi pieces. Each piece is coated in a delightfully crisp, golden breadcrumb that provides a fantastic crunch, yielding to the sweet, tender seafood inside. Served with a hearty portion of chips, garden peas, and a pot of tangy tartare sauce for dipping. The delicate, slightly sweet flavour of the scampi pairs beautifully with the sharp tartare and a squeeze of fresh lemon. It is an excellent choice for a lighter, yet highly comforting fish dish that is universally adored.',
    typicalPriceGbp: 8.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1135,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    availabilityNote: 'Fish Friday pricing on Fridays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Small Battered Cod and Chips',
    slug: 'small-battered-cod-chips',
    category: 'fish-dishes',
    description: 'A wonderfully manageable portion of our classic battered cod, perfect for those with a slightly lighter appetite who still crave traditional flavours. It features a smaller fillet of tender, flaky white cod encased in our signature crispy, golden batter. Served alongside a modest portion of thick-cut chips and your choice of mushy or garden peas. You still get all the fantastic textural contrasts—the crunchy batter and soft fish—without the overwhelming size of the large portion. This is an ideal choice for a lunchtime treat or a sensible, deeply satisfying early evening meal.',
    typicalPriceGbp: 7.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    availabilityNote: 'Fish Friday pricing on Fridays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Small Whitby Breaded Scampi',
    slug: 'small-whitby-breaded-scampi',
    category: 'fish-dishes',
    description: 'A perfectly portioned, lighter take on our popular breaded scampi, offering all the flavour in a smaller size. You receive a delightful serving of sweet, plump whole-tail scampi encased in crisp, golden breadcrumbs, accompanied by chips and garden peas. The crunchy exterior and tender seafood interior create a highly satisfying texture, while the tangy tartare sauce cuts through the richness beautifully. This is a brilliant choice for a quick lunch, a lighter dinner, or for older children wanting a grown-up meal. Served piping hot, it is consistently delicious and completely fuss-free.',
    typicalPriceGbp: 6.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    availabilityNote: 'Fish Friday pricing on Fridays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Tuna Mayo Jacket Potato',
    slug: 'tuna-mayo-jacket-potato',
    category: 'fish-dishes',
    description: 'A beautifully simple, wholesome, and highly comforting lunchtime classic. A large, fluffy oven-baked jacket potato with a wonderfully crisp skin is split open and generously filled with a creamy, savoury mixture of flaked tuna and rich mayonnaise. Served alongside a fresh, crisp side salad dressed with a light vinaigrette. The contrast between the hot, earthy potato and the cool, creamy tuna filling creates a deeply satisfying eating experience. It is an excellent, naturally gluten-free option for a nutritious and filling lunch that leaves you feeling perfectly satisfied without being overly heavy.',
    typicalPriceGbp: 6.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['fish', 'eggs', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Fish Finger Sandwich',
    slug: 'fish-finger-sandwich',
    category: 'fish-dishes',
    description: 'A nostalgic and incredibly comforting treat that brings childhood memories rushing back. Thick, crispy breaded cod fish fingers are layered generously between soft, fresh slices of white or malted bread. The sandwich is elevated with a healthy smear of sharp, tangy tartare sauce, which cuts through the richness of the breaded fish perfectly. The contrast of the soft bread and the crunchy fish fingers creates a phenomenal texture profile. It is the absolute perfect choice for a quick, warming lunch or a casual afternoon snack, best enjoyed with a hot cup of tea.',
    typicalPriceGbp: 6.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 780,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    availabilityNote: 'Fish Friday pricing on Fridays',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Prawn Cocktail',
    slug: 'prawn-cocktail',
    category: 'fish-dishes',
    description: 'A timeless and sophisticated retro starter that never fails to impress. This dish features a generous portion of sweet, delicate coldwater prawns, generously coated in a rich, tangy, and slightly sweet Marie Rose sauce. They are elegantly presented over a bed of crisp, fresh iceberg lettuce, offering a wonderful contrast of soft and crunchy textures. Accompanied by slices of buttered bread to scoop up the delicious sauce. It is a brilliant, light, and refreshing choice to begin a larger meal, providing a clean and classic flavour profile that prepares the palate perfectly.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'crustaceans', 'eggs', 'milk'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Sunday Roasts (5 items)
  {
    name: 'Roast Beef',
    slug: 'roast-beef',
    category: 'sunday-roasts',
    description: 'A truly magnificent Sunday staple that delivers supreme comfort and traditional flavours. This dish features generous, tender slices of premium roast beef, cooked to perfection to ensure a deep, savoury taste. It is served with a towering, crisp Yorkshire pudding, fluffy roasted potatoes with a golden crunch, a medley of fresh seasonal vegetables, and a rich, dark meat gravy. The combination of the succulent beef and the savoury gravy soaking into the Yorkshire pudding creates an incredible texture. It is the ultimate choice for a relaxing Sunday afternoon meal with family or friends.',
    typicalPriceGbp: 9.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 984,
    allergens: ['cereals containing gluten', 'eggs', 'milk'],
    dietaryTags: [],
    availabilityNote: 'Available Sundays only',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Roast Chicken Breast',
    slug: 'roast-chicken-breast',
    category: 'sunday-roasts',
    description: 'A delightful and deeply comforting traditional Sunday lunch featuring a plump, succulent roasted chicken breast. The meat is incredibly tender and mild, absorbing the rich flavours of the accompanying savoury gravy beautifully. Served with all the classic trimmings, including a crisp, oversized Yorkshire pudding, golden roasted potatoes, and a vibrant selection of seasonal vegetables. The crispy skin of the potatoes and the soft Yorkshire pudding offer fantastic textural variety. This is a wonderful, slightly lighter alternative to beef, perfect for those who want a classic, wholesome weekend feast. Served piping hot.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1302,
    allergens: ['cereals containing gluten', 'eggs', 'milk'],
    dietaryTags: [],
    availabilityNote: 'Available Sundays only',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Roast Pork',
    slug: 'roast-pork',
    category: 'sunday-roasts',
    description: 'A phenomenal Sunday roast that boasts an incredibly rich and savoury flavour profile. This dish stars succulent, tender slices of slow-roasted pork, complete with a highly coveted piece of salty, crispy crackling. Accompanied by a large, crisp Yorkshire pudding, golden roasted potatoes, fresh seasonal vegetables, and a generous pour of rich gravy. The contrast between the melt-in-the-mouth pork and the sharp crunch of the crackling is simply spectacular. It is an outstanding choice for diners seeking a deeply traditional, hearty, and indulgent end to the week. Served steaming hot and highly satisfying.',
    typicalPriceGbp: 9.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 1028,
    allergens: ['cereals containing gluten', 'eggs', 'milk'],
    dietaryTags: [],
    availabilityNote: 'Available Sundays only',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegetarian Wellington',
    slug: 'vegetarian-wellington',
    category: 'sunday-roasts',
    description: 'A spectacular meat-free centrepiece that ensures vegetarians do not miss out on the joy of a traditional Sunday roast. This savoury wellington features a rich, earthy blend of mushrooms, creamy melted brie, and sweet cranberries, all beautifully encased in a crisp, golden puff pastry lattice. Served with crisp roast potatoes, seasonal vegetables, a Yorkshire pudding, and a rich vegetarian gravy. The flaky pastry, gooey cheese, and sweet cranberries create a highly complex and luxurious flavour profile. It is a fantastic, indulgent choice that even meat-eaters will eye with envy. Served piping hot.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'eggs', 'milk'],
    dietaryTags: ['vegetarian'],
    availabilityNote: 'Available Sundays only',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegan Wellington',
    slug: 'vegan-wellington',
    category: 'sunday-roasts',
    description: 'A brilliant and highly satisfying plant-based roast dinner option that delivers robust, wholesome flavours. This wellington features a hearty, savoury vegetable and pulse filling, wrapped in a perfectly crisp and flaky vegan pastry. It is accompanied by golden roasted potatoes, a vibrant array of fresh seasonal vegetables, and a deep, flavourful vegan gravy. The contrasting textures of the crisp pastry and the tender filling provide a wonderful eating experience. It is an excellent choice for vegans and flexitarians wanting a deeply comforting, traditional Sunday meal without any animal products. Served hot and fresh.',
    typicalPriceGbp: 8.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegan', 'vegetarian'],
    availabilityNote: 'Available Sundays only',
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Desserts (8 items)
  {
    name: 'Warm Chocolate Fudge Cake',
    slug: 'chocolate-fudge-cake',
    category: 'desserts',
    description: 'An absolute triumph of a dessert, offering a wonderfully decadent and incredibly rich chocolate experience. This large slice of layered chocolate fudge cake is wonderfully dense and moist, served gloriously warm so the rich fudge icing begins to melt gently. You can choose to have it accompanied by a scoop of soft vanilla ice cream or a generous pour of piping hot custard. The contrast between the hot, sticky cake and the cold ice cream creates a phenomenal texture profile. It is the ultimate choice for dedicated chocoholics needing a highly comforting, sweet finish.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 832,
    allergens: ['cereals containing gluten', 'eggs', 'milk', 'soybeans'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Sticky Toffee Pudding',
    slug: 'sticky-toffee-pudding',
    category: 'desserts',
    description: 'A profoundly comforting and traditional British dessert that never disappoints. This incredibly moist, dark sponge pudding is absolutely drenched in a rich, sweet, and buttery toffee sauce. It is best enjoyed served warm with a scoop of melting vanilla ice cream or thick hot custard. The sponge is wonderfully light yet rich, and the toffee sauce provides a deep, caramelised flavour profile that is incredibly satisfying. It is an outstanding choice for warming up on a chilly evening, offering a deeply nostalgic and indulgent end to any hearty pub meal.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 750,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Bramley Apple Crumble',
    slug: 'bramley-apple-crumble',
    category: 'desserts',
    description: 'The definitive British pub dessert, balancing sweet and tart flavours with absolute perfection. Deeply flavoured, slightly tart Bramley apples are baked until wonderfully soft, sitting beneath a thick layer of buttery, golden crumble topping that provides a highly satisfying crunch. This deeply comforting dish is best enjoyed flooded with steaming hot, creamy custard, which mellows the tartness of the apples beautifully. The contrast of the crunchy topping, soft fruit, and smooth custard creates a phenomenal texture. It is a superb choice for a traditional, warming treat that feels like a warm hug.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 580,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Millionaires Dessert',
    slug: 'millionaires-dessert',
    category: 'desserts',
    description: 'A spectacular and highly indulgent sundae that brings together a brilliant array of textures and sweet flavours. This tall glass is layered with generous scoops of soft vanilla ice cream, crumbly buttery shortbread pieces, and lavish drizzles of both rich Belgian chocolate sauce and sweet sticky toffee sauce. The crunch of the biscuit against the smooth, cold ice cream provides a delightful eating experience, while the dual sauces offer a complex, luxurious sweetness. It is a fantastic choice for those who want a fun, decadent, and highly satisfying dessert to share or devour alone.',
    typicalPriceGbp: 3.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk', 'soybeans'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Mini Warm Chocolate Brownie',
    slug: 'mini-chocolate-brownie',
    category: 'desserts',
    description: 'A perfectly formed, slightly smaller dessert option for when you crave a sweet finish but lack the appetite for a massive pudding. This incredibly dense, fudgy chocolate brownie is served delightfully warm, topped with a rich Belgian chocolate sauce and a scoop of soft vanilla ice cream. Despite its smaller size, it delivers an intensely rich and satisfying chocolate hit. The contrast of the warm, gooey brownie and the melting cold ice cream is sublime. It is an ideal choice to accompany an after-dinner coffee, providing a neat, highly indulgent conclusion to your meal.',
    typicalPriceGbp: 3.29,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 697,
    allergens: ['cereals containing gluten', 'eggs', 'milk', 'soybeans'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Fresh Fruit with Ice Cream',
    slug: 'fresh-fruit-ice-cream',
    category: 'desserts',
    description: 'A wonderfully light and refreshing conclusion to a heavy meal, offering a vibrant burst of natural sweetness. This dish features a colourful medley of freshly chopped, seasonal fruit pieces, served alongside a generous scoop of soft, creamy vanilla ice cream. The crisp, juicy textures of the fruit contrast beautifully with the rich, smooth ice cream, providing a clean and palate-cleansing flavour profile. It is an excellent choice for diners seeking a lighter, slightly healthier dessert option that still feels like a proper treat. Served chilled, it is particularly delightful on a warm afternoon.',
    typicalPriceGbp: 3.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 420,
    allergens: ['milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Vegan Chocolate Tart',
    slug: 'vegan-chocolate-tart',
    category: 'desserts',
    description: 'A highly sophisticated and completely plant-based dessert that refuses to compromise on indulgence. This elegant tart features an incredibly rich, smooth, and dark chocolate filling, perfectly set within a crisp, crumbly chocolate pastry case. It is served chilled with a scoop of high-quality vegan vanilla ice cream. The deep, intense cocoa flavours are beautifully balanced by the creamy, subtle sweetness of the ice cream, while the pastry provides a highly satisfying crunch. This is a brilliant choice for vegans or anyone who appreciates a dark, intense chocolate dessert. It is deeply satisfying and luxurious.',
    typicalPriceGbp: 4.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'eggs', 'milk', 'soybeans'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'British Bramley Apple & Blackberry Crumble',
    slug: 'apple-blackberry-crumble',
    category: 'desserts',
    description: 'A delightful, rustic variation of our standard crumble, bringing a wonderful woodland twist to a pub classic. Sweet, deeply coloured blackberries are baked together with tart Bramley apples, sitting beneath a thick, buttery, golden crumble topping. The dark berries add a complex, fruity depth and a stunning purple hue to the dish. Best served piping hot with a generous pour of creamy custard, the combination of crunchy topping, soft, sweet-tart fruit, and smooth custard is simply exceptional. It is a superb choice for a highly comforting, traditional pudding with a beautiful fruity brightness.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Drinks Menu (15 items)
  {
    name: 'Pint of Ruddles Best',
    slug: 'pint-ruddles-best',
    category: 'drinks-menu',
    description: 'A classic, highly reliable English bitter that is famous across the network for its unbeatable value and traditional character. Pouring a clear copper colour, it offers a wonderfully balanced flavour profile featuring robust toasted malt notes, a subtle hint of caramel sweetness, and a gentle, earthy hop bitterness on the finish. It is served chilled on draft with a smooth, creamy head. This easy-drinking session ale pairs brilliantly with traditional pub dishes like the classic beef burger or the steak and kidney pudding, providing a highly satisfying, unpretentious pint for the traditional ale drinker.',
    typicalPriceGbp: 1.79,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Pint of Doom Bar',
    slug: 'pint-doom-bar',
    category: 'drinks-menu',
    description: 'An exceptionally popular and highly regarded amber ale hailing from Cornwall, known for its incredible consistency and drinkability. It boasts a beautiful amber hue and delivers a balanced, slightly sweet flavour profile with distinct notes of roasted malt, a touch of dried fruit, and a clean, lightly bitter finish. Served cold on draft, it offers a smooth, highly refreshing mouthfeel. This versatile ale is an excellent companion to roasted meats, making it the perfect pairing for our Sunday roast beef or a hearty mixed grill. A brilliant choice for both seasoned and novice ale drinkers.',
    typicalPriceGbp: 2.29,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Pint of Stella Artois',
    slug: 'pint-stella-artois',
    category: 'drinks-menu',
    description: 'A premium, internationally renowned Belgian-style lager that delivers a crisp, highly refreshing drinking experience. Pouring a bright, pale golden colour with a thick white head, it offers a clean, sophisticated flavour profile with subtle floral hop aromas and a gentle, malty sweetness, finishing with a satisfying, crisp bitterness. Served wonderfully chilled on draft, its high carbonation effectively cleanses the palate. This sharp, bright lager pairs exceptionally well with our battered cod and chips or spicy chicken dishes, cutting through the richness beautifully. It is a steadfast, high-quality choice for lager enthusiasts.',
    typicalPriceGbp: 3.89,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Pint of Guinness',
    slug: 'pint-guinness',
    category: 'drinks-menu',
    description: 'The iconic, globally celebrated Irish dry stout, famous for its mesmerising cascade and dense, creamy white head. Pouring a deep, ruby-black hue, it offers a highly complex flavour profile featuring prominent notes of roasted barley, dark chocolate, and a distinct espresso-like bitterness, all balanced by a smooth, velvety texture. Served perfectly chilled on draft, the unique nitrogen surge creates a luxuriously soft mouthfeel. This robust stout is a phenomenal pairing for our deeply savoury beef madras or a rich chocolate fudge cake. It is the ultimate choice for those seeking a dark, highly comforting pint.',
    typicalPriceGbp: 3.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 210,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Pint of Thatchers Gold',
    slug: 'pint-thatchers-gold',
    category: 'drinks-menu',
    description: 'A brilliantly refreshing, medium-dry Somerset cider that perfectly captures the essence of English orchards. Pouring a bright, clear gold, it is packed with the vibrant, authentic taste of juicy, sun-drenched apples. The flavour profile offers a wonderful balance of natural apple sweetness and a subtle, crisp acidity, leading to a smooth, highly refreshing finish. Served wonderfully chilled on draft, it is an incredibly thirst-quenching option. This fruity cider pairs wonderfully with our roast pork or a classic margherita pizza, providing a bright, sweet contrast to savoury flavours. An excellent choice for a sunny afternoon.',
    typicalPriceGbp: 2.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['sulphur dioxide'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Large Pepsi Max',
    slug: 'large-pepsi-max',
    category: 'drinks-menu',
    description: 'A highly refreshing, large glass of the incredibly popular zero-sugar cola, delivering maximum taste without the calories. It offers a bold, crisp, and intensely sweet cola flavour profile with a lively, bubbly carbonation that dances on the tongue. Served ice-cold over plenty of ice cubes, it provides an exceptionally thirst-quenching experience. This versatile, sharp soft drink acts as a brilliant palate cleanser, making it an excellent pairing for our spicy meat feast pizza or a hearty BBQ bacon burger. It is the perfect choice for drivers or those wanting a substantial, highly refreshing non-alcoholic beverage.',
    typicalPriceGbp: 1.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 119,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Lavazza Filter Coffee',
    slug: 'lavazza-filter-coffee',
    category: 'drinks-menu',
    description: 'A freshly brewed, highly comforting cup of premium Lavazza filter coffee, renowned for its smooth and accessible character. It offers a well-rounded, medium-bodied flavour profile with gentle notes of roasted nuts and a subtle, naturally sweet undertone, completely devoid of any harsh bitterness. Served steaming hot in a ceramic mug, with the brilliant benefit of free refills all day. This clean, warming coffee is the ultimate companion to a traditional or vegan breakfast, providing a gentle, highly satisfying caffeine boost. It is a steadfast choice for early mornings or relaxed afternoon reading sessions.',
    typicalPriceGbp: 1.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 5,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Lavazza Cappuccino',
    slug: 'lavazza-cappuccino',
    category: 'drinks-menu',
    description: 'A rich, highly satisfying, and beautifully textured Italian classic. This drink features a robust shot of premium Lavazza espresso, which provides a deep, complex coffee base, topped generously with velvety steamed milk and a thick, luxurious cap of airy milk foam. A light dusting of chocolate powder adds a gentle sweetness. The contrast between the intense espresso and the sweet, creamy milk creates a wonderfully balanced flavour profile. Served steaming hot, it is an excellent choice for a mid-morning treat or as a comforting digestif after a large meal, pairing perfectly with a mini brownie.',
    typicalPriceGbp: 1.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 95,
    allergens: ['milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Smirnoff Red Vodka & Mixer',
    slug: 'smirnoff-vodka-mixer',
    category: 'drinks-menu',
    description: 'A clean, crisp, and highly versatile classic spirit and mixer combination. Featuring a precise single measure of the world-renowned Smirnoff Red label vodka, which provides a remarkably smooth, neutral spirit base. You have the freedom to pair it with your choice of draft mixer, such as cola or lemonade, served over a generous handful of ice. The flavour profile is highly refreshing and entirely dependent on your chosen mixer, making it an incredibly adaptable drink. It is a fantastic, fuss-free choice for a lively evening out or a relaxed weekend drink, offering clean and simple refreshment.',
    typicalPriceGbp: 2.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Gordon’s Gin & Tonic',
    slug: 'gordons-gin-tonic',
    category: 'drinks-menu',
    description: 'The quintessential British mixed drink, offering a highly sophisticated and deeply refreshing botanical experience. This classic features a single measure of Gordon’s London Dry gin, renowned for its bold, piney juniper notes and subtle hints of coriander and citrus. It is served over plenty of ice and topped with a premium bottle of crisp, slightly bitter tonic water, garnished with a fresh slice of lemon or lime. The sharp, clean flavour profile makes it an exceptional palate cleanser, pairing brilliantly with lighter dishes like the prawn cocktail. It is a timeless, elegant choice for any occasion.',
    typicalPriceGbp: 3.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Coldwater Creek Pinot Grigio (175ml)',
    slug: 'coldwater-creek-pinot-grigio-175ml',
    category: 'drinks-menu',
    description: 'A delightfully crisp, dry, and highly refreshing white wine that is incredibly easy to drink. Pouring a pale straw colour, it offers a bright, zesty flavour profile with subtle notes of green apple, juicy pear, and a hint of sharp citrus. Served wonderfully chilled in a 175ml glass, it provides a clean, acidic finish that enlivens the palate. This light, elegant wine is an absolutely perfect pairing for our freshly battered cod or a vibrant side salad, cutting through any richness beautifully. It is a fantastic choice for a warm afternoon or a light evening meal.',
    typicalPriceGbp: 3.29,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['sulphur dioxide'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Coldwater Creek Merlot (175ml)',
    slug: 'coldwater-creek-merlot-175ml',
    category: 'drinks-menu',
    description: 'A wonderfully smooth, approachable, and highly comforting red wine that boasts a deeply fruity character. Pouring a rich ruby red, it delivers a soft, velvety flavour profile packed with notes of ripe dark plums, sweet black cherries, and a subtle hint of warming spice. Served at a pleasant room temperature in a 175ml glass, its low tannins ensure a highly drinkable, mellow finish. This versatile red wine pairs exceptionally well with our classic 6oz beef burger or a hearty bowl of beef madras, complementing the savoury meats perfectly. A brilliant choice for a cosy evening.',
    typicalPriceGbp: 3.29,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['sulphur dioxide'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kopparberg Mixed Fruit',
    slug: 'kopparberg-mixed-fruit',
    category: 'drinks-menu',
    description: 'A massively popular, premium Swedish cider that offers an incredibly sweet and vibrant fruity experience. Pouring a deep, bright reddish-purple, it is bursting with the intense, juicy flavours of ripe blackcurrants and sweet raspberries, effectively masking any sharp apple notes. It must be served heavily chilled over a mountain of ice to ensure maximum refreshment and to balance the profound sweetness. This highly refreshing, candy-like cider is a fantastic standalone drink for a sunny pub garden, or pairs well with light, salty snacks. It is the ultimate choice for those with a serious sweet tooth.',
    typicalPriceGbp: 4.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['sulphur dioxide'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'J2O Orange & Passion Fruit',
    slug: 'j2o-orange-passion-fruit',
    category: 'drinks-menu',
    description: 'A phenomenally popular, highly refreshing, and completely non-carbonated fruit juice blend. It boasts a vibrant orange hue and delivers a wonderfully thick, smooth texture. The flavour profile perfectly balances the sharp, zesty tang of ripe oranges with the exotic, tropical sweetness of passion fruit, creating a deeply satisfying, full-bodied taste. Served chilled in its iconic glass bottle, it is an outstanding premium soft drink option. This sweet, fruity beverage pairs brilliantly with spicy dishes like the chicken jalfrezi, helping to cool the palate. An excellent, sophisticated choice for non-drinkers or older children.',
    typicalPriceGbp: 2.19,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 95,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Diet Coke (Pint)',
    slug: 'pint-diet-coke',
    category: 'drinks-menu',
    description: 'A highly refreshing, generous pint of the world-famous calorie-free cola, served straight from the draft lines. It offers a distinctively crisp, sharp, and uniquely sweet flavour profile with a bright, lively carbonation that provides an intense mouthfeel. Served ice-cold, it is an incredibly thirst-quenching option that cleanses the palate brilliantly between bites. This versatile soft drink is a fantastic pairing for absolutely any dish on the menu, from a rich steak to a simple margherita pizza. It is a reliable, highly satisfying choice for those seeking maximum refreshment without the sugar or alcohol.',
    typicalPriceGbp: 1.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Sides (7 items)
  {
    name: 'Bowl of Chips',
    slug: 'bowl-of-chips',
    category: 'sides',
    description: 'A highly generous and deeply comforting bowl of our famous thick-cut pub chips. Cooked until they achieve a spectacular golden-brown, crispy exterior while remaining wonderfully soft and fluffy on the inside. They boast a rich, savoury potato flavour that is incredibly satisfying. This essential side dish is the perfect complement to almost any main meal, particularly burgers and steaks, or serves brilliantly as a hearty, shareable snack over a few pints. Served piping hot, they are an absolute staple of the British pub experience that never fails to hit the spot.',
    typicalPriceGbp: 3.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 602,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Bowl of Chips with Cheese',
    slug: 'bowl-chips-cheese',
    category: 'sides',
    description: 'An incredibly indulgent and highly satisfying upgrade to our classic side dish. We take a generous bowl of our hot, crispy, thick-cut golden chips and smother them in a thick, luxurious layer of melting cheddar cheese. The gooey, salty cheese seeps into the crispy chips, creating a phenomenal, rich texture and a deeply savoury flavour profile. It is a fantastic, highly comforting side that pairs beautifully with a simple grilled chicken burger, or serves as a wonderfully decadent, standalone snack to share with friends. Served steaming hot, it is pure, unadulterated comfort food.',
    typicalPriceGbp: 4.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 602,
    allergens: ['milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Onion Rings (Six)',
    slug: 'onion-rings-six',
    category: 'sides',
    description: 'A fantastic, highly satisfying side dish featuring six exceptionally large, thick-cut onion rings. Each ring is generously coated in a light, seasoned batter and fried until it achieves a spectacular, crispy golden-brown finish. The crunch of the exterior yields to a beautifully soft, sweet, and tender onion inside, offering a wonderful textural contrast. These savoury, slightly sweet rings are the ultimate accompaniment to a hearty steak or a towering beef burger, adding a brilliant crunch to your meal. Served piping hot, they are a universally adored pub classic that always delivers on flavour.',
    typicalPriceGbp: 2.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 269,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Garlic Pizza Bread',
    slug: 'garlic-pizza-bread',
    category: 'sides',
    description: 'A highly aromatic and deeply satisfying side dish that is perfect for sharing. We take an 8-inch, thin and crispy pizza base and generously smother it in a rich, luxurious garlic and herb butter. Baked in the oven until the edges are wonderfully crisp and golden, the bread absorbs the pungent, savoury garlic flavour beautifully. The texture is a delightful mix of a crunchy crust and a slightly soft, buttery centre. It is the perfect complement to our pasta dishes or a fresh salad, providing a comforting, highly flavourful addition to any meal. Served hot.',
    typicalPriceGbp: 3.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Garlic Pizza Bread with Cheese',
    slug: 'garlic-pizza-bread-cheese',
    category: 'sides',
    description: 'A phenomenally indulgent twist on a classic side dish, combining rich garlic with gooey dairy. Our crisp, 8-inch garlic and herb pizza bread is elevated by a thick, generous layer of melting mozzarella cheese. Baked until the cheese is beautifully golden and bubbling, it offers a highly complex flavour profile of sharp garlic and mild, creamy cheese. The texture is incredibly satisfying, with the stretchy cheese contrasting the crisp pizza base. It serves as an outstanding, rich accompaniment to our lighter salads or as a fantastic, highly shareable starter. Served piping hot from the oven.',
    typicalPriceGbp: 4.49,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Side Salad',
    slug: 'side-salad',
    category: 'sides',
    description: 'A wonderfully crisp, light, and highly refreshing side dish that brings a vibrant burst of colour to your meal. It features a fresh, crunchy mix of torn iceberg lettuce, juicy cherry tomatoes, crisp cucumber slices, and sharp red onion rings, all lightly tossed in a zesty, tangy vinaigrette dressing. The bright acidity of the dressing perfectly cuts through the richness of heavier main meals. It is an excellent, healthy complement to a rich lasagne or a hearty burger, providing a clean, fresh textural contrast that enlivens the palate. Served wonderfully chilled and crisp.',
    typicalPriceGbp: 1.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 87,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Mushy Peas',
    slug: 'side-mushy-peas',
    category: 'sides',
    description: 'The absolute quintessential, highly traditional accompaniment to any battered fish dish. These classic chip shop style mushy peas are cooked down to a wonderfully thick, rich, and creamy consistency. They boast a distinctively sweet, earthy flavour profile and a vibrant green colour that brightens up the plate. The soft, smooth texture provides a phenomenal contrast to the sharp crunch of battered cod or crispy chips. Highly comforting and deeply nostalgic, they are an essential addition for anyone seeking the authentic British fish and chip experience. Served steaming hot, they are simple yet completely indispensable.',
    typicalPriceGbp: 0.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: [],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },

  // Kids Menu (7 items)
  {
    name: 'Kids Chicken Nuggets',
    slug: 'kids-chicken-nuggets',
    category: 'kids-menu',
    description: 'A highly reliable and deeply comforting favourite that children absolutely adore. This meal features five premium, battered chicken breast nuggets that offer a fantastic, mild savoury flavour and a highly satisfying crunch. Served with a choice of thick-cut chips or fun, crispy potato smiley faces, alongside a healthy portion of baked beans or sweet garden peas. The varying textures keep the meal exciting and enjoyable for younger palates. It is a brilliant, fuss-free choice for a guaranteed clean plate. Crucially, this meal includes a refreshing children’s drink and a piece of fresh fruit for dessert.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 520,
    allergens: ['cereals containing gluten', 'milk', 'eggs'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Sausages and Mash',
    slug: 'kids-sausages-mash',
    category: 'kids-menu',
    description: 'A wonderfully hearty and highly traditional British comfort meal perfectly portioned for younger diners. It features two mild, savoury pork sausages served atop a mound of beautifully creamy, smooth mashed potato. Accompanied by sweet garden peas and a generous ladle of rich, dark gravy. The soft textures and rich, savoury flavours make it an incredibly comforting and easy-to-eat option. It is an excellent choice for a warming dinner on a colder day, providing wholesome, filling sustenance. This meal also conveniently includes a children’s drink and a piece of fresh fruit to finish.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'milk', 'soybeans'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Margherita Pizza',
    slug: 'kids-margherita-pizza',
    category: 'kids-menu',
    description: 'A fantastic, kid-friendly version of an Italian classic that never fails to please. This slightly smaller, manageable pizza features a thin, crispy base topped with a sweet, mild tomato sauce and a generous layer of gooey, melting mozzarella cheese. The simple, clean flavour profile and the fun, stretchy cheese make it highly appealing to younger diners, while the crisp base offers a satisfying crunch. It is an excellent, fuss-free vegetarian choice that is easy to eat and universally loved. Importantly, the meal is complete with a children’s drink and a piece of fresh fruit.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 959,
    allergens: ['cereals containing gluten', 'milk'],
    dietaryTags: ['vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Vegan Sausages',
    slug: 'kids-vegan-sausages',
    category: 'kids-menu',
    description: 'A brilliant, highly satisfying plant-based meal designed specifically for younger appetites. This dish features two savoury, mild Quorn vegan sausages that offer a fantastic, meat-like texture without any animal products. They are paired with a child-sized portion of our classic golden chips and a comforting serving of sweet baked beans. The familiar, mild flavours and comforting textures make it an incredibly accessible and enjoyable meat-free option. It is an ideal choice for vegan children or those exploring vegetarian diets. This complete meal also includes a refreshing children’s drink and a piece of fresh fruit.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'soybeans'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Fish Fingers',
    slug: 'kids-fish-fingers',
    category: 'kids-menu',
    description: 'A highly nostalgic, timeless childhood classic that provides a wonderful introduction to seafood. This meal stars three thick, premium breaded cod fish fingers, offering a fantastic crispy exterior and soft, flaky, mild white fish inside. Served alongside a portion of golden chips and sweet garden peas, providing a wonderfully colourful and texturally diverse plate. The mild, unchallenging flavours are perfect for younger palates, making it a highly reliable and popular choice. For a complete dining experience, this meal generously includes a children’s drink and a fresh piece of fruit for dessert.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: 650,
    allergens: ['cereals containing gluten', 'eggs', 'fish'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Tomato Pasta',
    slug: 'kids-tomato-pasta',
    category: 'kids-menu',
    description: 'A wonderfully simple, highly comforting, and universally beloved dish for younger diners. It features a generous bowl of soft, easy-to-eat tubular pasta, thoroughly bound in a rich, sweet, and incredibly smooth tomato sauce. The mild, familiar flavours and soft textures make it an exceptionally accessible and fuss-free option, perfect for even the most selective of eaters. It is a fantastic, wholesome vegetarian choice that provides excellent energy for active children. To ensure a completely balanced meal, it is served with a children’s drink and a piece of fresh fruit to finish.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten'],
    dietaryTags: ['vegan', 'vegetarian'],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  },
  {
    name: 'Kids Beef Burger',
    slug: 'kids-beef-burger',
    category: 'kids-menu',
    description: 'A fantastic, simplified version of our pub classic, tailored perfectly for children. This meal features a smaller, mildly seasoned beef patty served in a soft, plain white bun without any complex sauces or salads. It is accompanied by a child-sized portion of our classic golden chips and a comforting side of sweet baked beans. The savoury, straightforward flavours and soft textures are highly appealing and easy to manage for younger diners. It is an excellent choice for kids wanting a grown-up pub meal. This meal also includes a children’s drink and a fresh piece of fruit.',
    typicalPriceGbp: 4.99,
    priceCheckedOn: '2026-10-01',
    caloriesKcal: null,
    allergens: ['cereals containing gluten', 'sesame'],
    dietaryTags: [],
    sourceLabel: 'Typical Wetherspoon menu board',
    lastReviewedOn: '2026-10-01'
  }
];
